"""Add updatedAt to Habit

Revision ID: 061d051c8aa2
Revises: fdf29d311c49
Create Date: 2024-01-20 21:58:23.673016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061d051c8aa2'
down_revision = 'fdf29d311c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
