"""Remove old logic

Revision ID: 8a54533de1ca
Revises: 59bfc7da2e6d
Create Date: 2024-01-20 17:06:16.127373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a54533de1ca'
down_revision = '59bfc7da2e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anonim_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonim_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name='anonim_message_receiver_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='anonim_message_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='anonim_message_pkey')
    )
    # ### end Alembic commands ###
