"""Added_new_timestamps

Revision ID: b3835d76370a
Revises: b78feb9bd746
Create Date: 2024-01-20 20:20:21.302493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3835d76370a'
down_revision = 'b78feb9bd746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheerup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_new', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cheerup_timestamp_new'), ['timestamp_new'], unique=False)

    with op.batch_alter_table('daily_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_new', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_daily_update_timestamp_new'), ['timestamp_new'], unique=False)

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_new', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp_broken_new', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('timestamp_broken_new')
        batch_op.drop_column('timestamp_new')

    with op.batch_alter_table('daily_update', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_update_timestamp_new'))
        batch_op.drop_column('timestamp_new')

    with op.batch_alter_table('cheerup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cheerup_timestamp_new'))
        batch_op.drop_column('timestamp_new')

    # ### end Alembic commands ###
