"""Added timestampBroken

Revision ID: b78feb9bd746
Revises: 384f67f9ac4e
Create Date: 2024-01-20 18:46:54.669450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78feb9bd746'
down_revision = '384f67f9ac4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_broken', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('timestamp_broken')

    # ### end Alembic commands ###
