"""added_sus_message

Revision ID: dfd777944a68
Revises: 061d051c8aa2
Create Date: 2024-01-20 22:43:42.865691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd777944a68'
down_revision = '061d051c8aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspicious_message', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_update', schema=None) as batch_op:
        batch_op.drop_column('suspicious_message')

    # ### end Alembic commands ###
