"""Add DialyUpdate and Cheerup

Revision ID: ecda84adec9c
Revises: 8a54533de1ca
Create Date: 2024-01-20 17:14:08.207093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecda84adec9c'
down_revision = '8a54533de1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_cheered', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_update', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_update_timestamp'), ['timestamp'], unique=False)

    op.create_table('cheerup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['update_id'], ['daily_update.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cheerup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cheerup_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheerup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cheerup_timestamp'))

    op.drop_table('cheerup')
    with op.batch_alter_table('daily_update', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_update_timestamp'))

    op.drop_table('daily_update')
    # ### end Alembic commands ###
