"""remove_old_fields

Revision ID: f0399032df3e
Revises: b3835d76370a
Create Date: 2024-01-20 20:22:30.937400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0399032df3e'
down_revision = 'b3835d76370a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheerup', schema=None) as batch_op:
        batch_op.drop_index('ix_cheerup_timestamp')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('daily_update', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_update_timestamp')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('timestamp_broken')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_broken', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('daily_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_daily_update_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('cheerup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_cheerup_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
